name: Conditional Demo

on:
  push:
  pull_request:

jobs:

  conditional-job:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:

      - name: Step only on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running on main branch"

      - name: Force failure
        run: exit 1
        continue-on-error: true

      - name: Run if previous step failed
        if: failure()
        run: echo "Previous step failed"
