name: PR Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print branch
        run: |
          echo "PR check running for branch: ${{ github.head_ref }}"
