name: Scheduled Workflow

on:
  schedule:
    #- cron: '0 0 * * *'

jobs:
  schedule-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run scheduled job
        run: echo "This workflow runs every day at midnight UTC"
